### ISSUE TITLE
Rocket.Chat.PWA in React

### ISSUE THREAD

**Issue by inf3cti0n95** [RocketChat/Rocket.Chat.PWA#20]
I wanted to ask I am making the Rocket Chat PWA in React and If I can get a Repository for It. That way more contributors can contribute to it . And It'll be helpful to me and everyone. I can transfer ownership of my current repository of the App that I am making with @karlprieb 

Link to tge Rocket.Chat.PWA.React repository https://github.com/inf3cti0n95/Rocket.Chat.PWA.React

**Comment by karlprieb** [comment]
We created the [Official React PWA repository](https://github.com/RocketChat/Rocket.Chat.PWA.React) :)
