### ISSUE TITLE
Bugs in UI of login component

### ISSUE THREAD

**Issue by ajayns** [RocketChat/Rocket.Chat.PWA#35]
![image](https://user-images.githubusercontent.com/20743219/34381015-c4bed9ca-eb2b-11e7-9d9b-9bf66a39f9af.png)
The input boxes by material design should just have an underline and not the red full border.
I'd like to take up this issue. @InsaneNaman @karlprieb

**Comment by InsaneNaman** [comment]
@ajayns I agree. Please check the current status of the repo. If its the same then u can start working on this. https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown

Here is the reference link. :smile:

**Comment by ajayns** [comment]
@InsaneNaman Okay sure will do!

**Comment by ajayns** [comment]
Okay the previous issue has been solved but a new UI bug has come up. 
![image](https://user-images.githubusercontent.com/20743219/34904164-26c36770-f866-11e7-83af-a2b825af6d98.png)

There seems to be an issue with the right padding. I'll work on this issue? @InsaneNaman @karlprieb
